### PR TITLE
Version - 1

### PR DESCRIPTION
**Pull request by heintayzar-hm**
I added : the js-bundling and webpack

- Do crud operations
- get random messages

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @heintayzar-hm , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't use the correct git-flow, also the readme file still has the Microverse logo and descriptive messages in almost all sections as shown below 
image


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by heintayzar-hm** [comment]
@danmainah what do you mean by incorrect gitflow?

**Comment by danmainah** [comment]
> @danmainah what do you mean by incorrect git-flow?

@heintayzar-hm Instead of adding new features to the feature branch and then merging the changes in the dev branch instead of what you have done now, your base branch is supposed to be the dev branch and not the master branch.

**Comment by heintayzar-hm** [comment]
Ah , you want me to make a pr into dev from feature? Ok that is fine as well.

**Comment by heintayzar-hm** [comment]
I am very sorry if you are reviewing this, according to previous reviewer, I have moved the pr to https://github.com/heintayzar-hm/messages_generator/pull/2 You can invalid review or changes required. I am sorry.

**Pull request closed without merging**
